### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by benjamin051000** [KeethSmith/DD_Grader#1]
@KeethSmith I am maintaining a fork of this repository. If you no longer want to be the "upstream maintainer," I would recommend linking my fork (https://github.com/benjamin051000/DD_Grader) in your readme and archiving this repo (in settings).

**Comment by benjamin051000** [comment]
I have submitted a request to remove the forked relationship between this repo and the actively maintained one. The best course of action is likely to archive this repository so users know it is no longer maintained. 

Thanks for creating this awesome project! We use it every single semester :D

**Comment by KeethSmith** [comment]
Hey, thanks for checking this out! I’m glad this still works for the TA’s

**Comment by benjamin051000** [comment]
No problem! I put a lot of work into it on Arc Lab. Unfortunately, since Dr. Stitt left UF, I've heard from current TAs (I graduated last year) that Dr. Bobda does not intend on using it for the time being. But they are aware of the tools and should be able to adapt them easily to new assignments. Time will tell 🤷🏼 

The grader was incredibly useful for several years :D thanks again!
